trainer:
  name: Trainer
  num_epochs: 10

# dataset:
#   name: MNIST
#   root: data
#   batch_size: 32

model:
  name: CNN
  num_filters: 32
  filter_h:  3
  filter_w: 3
  image_channels: 1
  rank: 1
  num_class: 10

optimizer:
  name: SGD
  lr: 1.e-3

scheduler:
  name: StepLR
  step_size: 10
